apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-fss-pvc
  namespace: openclaw
  labels:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/part-of: openclaw
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: openclaw-fss-pv

