apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - fss-pv.yaml
  - fss-pvc.yaml
  - otel-configmap.yaml
  - openclaw-instance.yaml
  - tailscale-ingress.yaml
  - metrics-service.yaml
  - metrics-servicemonitor.yaml
  - metrics-networkpolicy.yaml
